dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
    # This will be part of the release tarball
    # TODO change the project name
    - CRATE_NAME=lonlat_bng
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    # GH_TOKEN
    - secure: bW+621HpryUdRObWedUlzgwrQ+lRrqN2S4MiMNJX9oa2I1/B4AM26QQDn604q9Hb+lRSO3S8SPqzvj7RqyCL+dmhR+vwf5Evyk+StR3aDAIAvXk1pl6w37ZoEJu4LPEUMpFjyTsOZ9CWj7KY1dqLo5fXV0iMd71m3yrNMLLaRRH6p9lV3tpIHu3IET5KrGcP4w1UNJtur116RAjtxS/lrraUUanTVepUidmnYdQGtpY1f1/1WDh4+J/oRyUws08FplUqsB1EFX0/zkVJbhShV1G85WUeZSFqZc7ij9H//3DJy05fzPhWbxUe4SXAMuaNaR1bOPiSUe+5HJbIgsg4vocBixRKkwj/I6hSzn35ODo/OyviWcb6u+DCJfq7ihhliH5JnKoX3Zn0RmTd4DL0jQNwsm136htpb7j1GeJ5GPT89lVZEss2pXBQhJWw4RU0goLbsgef3iw+RQ8r38TALh+MUGm8CjOjo8ESGQFkTIF3+9yJxF9XWuVx1sliI6dVgfbygFsRJWj2sas+TJJAT6gFqKYkGTZT6xkSds5JVfFVLIUDoSyJoJYwjpHnoBbPQfcQr8tRaw3XlhZpiSBnA/qCmjhTJ3W4VQEbhJtP4Ikf6GZmjMKuajW47pQHCf+egqgaYXiOAWZZ+iXzSB4R9OHi2inz1Lvw8YaIUe6p0o0=


# AFAICT There are a few ways to set up the build jobs. This one is not the DRYest but I feel is the
# easiest to reason about.
# TODO Feel free to remove the channels/targets you don't need
# NOTE Make *sure* you don't remove a reference (&foo) if you are going to dereference it (*foo)
matrix:
  include:
    # Stable channel
    # - os: osx
    #   rust: stable
    #   env: TARGET=i686-apple-darwin
    # - os: linux
    #   rust: stable
    #   env: TARGET=i686-unknown-linux-gnu
    #   addons:
    #     apt:
    #       packages: &i686_unknown_linux_gnu
    #         # Cross compiler and cross compiled C libraries
    #         - gcc-multilib

    ###############################
    - os: osx
      osx_image: xcode7.3
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      services: docker
    # Beta channel
    # - os: osx
    #   rust: beta
    #   env: TARGET=i686-apple-darwin
    # - os: linux
    #   rust: beta
    #   env: TARGET=i686-unknown-linux-gnu
    #   addons:
    #     apt:
    #       packages: *i686_unknown_linux_gnu
    ############################
    - os: osx
      rust: beta
      osx_image: xcode7.3
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu


    # Nightly channel
    # - os: osx
    #   rust: nightly
    #   env: TARGET=i686-apple-darwin
    # - os: linux
    #   rust: nightly
    #   env: TARGET=i686-unknown-linux-gnu
    #   addons:
    #     apt:
    #       packages: *i686_unknown_linux_gnu

    ############
    - os: osx
      osx_image: xcode7.3
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

  allow_failures:
    # Target `i686-unknown-linux-gnu` is currently only available on the nightly channel
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-gnu
    - os: linux
      rust: beta
      env: TARGET=i686-unknown-linux-gnu

before_install:
  - set -e

before_script: |
  PKGNAME="${TRAVIS_REPO_SLUG}" # must match with cargo.toml
  LOCAL="~/.local" # install here to avoid `sudo`
  pip install travis-cargo --user &&
  export PATH=$HOME/.local/bin:$PATH

install:
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - if [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then docker pull $DOCKER_IMAGE; fi

before_deploy:
  - if [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then sudo docker run -e TRAVIS_TAG="$TRAVIS_TAG" --rm -v `pwd`:/io $DOCKER_IMAGE /io/ci/manylinux_rust.sh; fi
  - if ! [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then bash ci/before_deploy.sh; fi
  # - sudo chown $USER ${CRATE_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  
deploy:
  # TODO Regenerate this api_key for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Call `travis encrypt $github_token` where $github_token is the token you got in the previous
  # step and `travis` is the official Travis CI gem (see https://rubygems.org/gems/travis/)
  # - Enter the "encrypted value" below
  api_key:
        - secure: DTWgwQjhzyIMwvdv6Sy+sLh0FoBOczxmRUO7wrBeahYK+wIz7ZfDkFp4j1pEeQYgHtB6hxEaYSKojNxHHvqCWkM5WtDm/cdU9tGkyVsTHsh54DQGyardiV704eiIWkFtFrCSKYHcJ/CMuTTwmbNIZZG281puJoHhtAoutTAPXrFzYtAC2zYWx+cODs9UXbq3yus6UBQJ8srHTYbKJDUQYGSDpXI0QSKj5O9CUzrmd11sZ6ol7+Xjykv6me2YjHKX9NnxYfplVLnEgDHZeAD8GKIYpb8Lb0AgKtkZh4EU+hC/9+5bqFQukeSVczEnTQKkHOyM36rbqnXJz9U7ar4JTYLaRIz5Uawcn4Mk2gStx3V+8TvzOd4rGpdRhFPVSiZzS+nwvTgmSowuo2bY/x8nXVEP2BqBUp98I4H36GtAk+xmRTl8ORmg+TytQJUGgnN1cmT0NAaGLdqfNUJ+eNBHP+hc0lLDelaYlEEOMq4G3NyTrYHgrDCcm9dmvB2znZLJGvVOZqLkH90DRxIpQ6VSFnt2n59oa2fKas6gjeWpsMY3OwrBj5lSe7yWM4cZvSmoBHQO1kAr13HrP8y/opFV+HeXWva9hwWSWAo8W7Lib8XXC+uBYwKPfO83QP2N+mr6gwdjgd5HTAMmmnAoRjOrcGlNIk3HfAXClGNcz3sLk3I=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
