[package]
name = "lonlat_bng"
description = "Convert longitude and latitude coordinates to BNG coordinates, and vice versa"
version = "0.2.3"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
license = "MIT"
keywords = ["OSGB36", "Geo", "FFI", "ETRS89", "OSTN02"]
repository = "https://github.com/urschrei/lonlat_bng"
documentation = "https://urschrei.github.io/lonlat_bng/"
readme = "README.md"

[dependencies]
libc = "0.2.7"
rand = "0.3.14"
crossbeam = "0.2.8"
num_cpus = "0.2.10"
# nalgebra = "0.5.1"
ostn02_phf = "0.1.7"

[lib]
name = "lonlat_bng"
crate-type = ["rlib", "dylib", "staticlib"]
test = true
doctest = false
doc = true

# [profile.release]
# debug = true

[[bin]]
name = "lonlat_bin"
doc = false
