[package]
name = "lonlat_bng"
description = "Convert longitude and latitude coordinates to BNG coordinates, and vice versa"
version = "0.4.3"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
license = "MIT"
keywords = ["OSGB36", "Geo", "FFI", "ETRS89", "OSTN02"]
repository = "https://github.com/urschrei/lonlat_bng"
documentation = "https://urschrei.github.io/lonlat_bng/"
readme = "README.md"

[dependencies]
libc = "0.2.15"
rand = "0.3.14"
# nalgebra = "0.5.1"
crossbeam = "0.2.9"
num_cpus = "0.2.13"
ostn15_phf = { git = "https://github.com/urschrei/ostn15_phf.git" }

[lib]
name = "lonlat_bng"
crate-type = ["dylib"]
test = true
doctest = false
doc = true

[profile.release]
rpath = true
# debug = true
