[package]
name = "lonlat_bng"
description = "Convert longitude and latitude coordinates to BNG coordinates, and vice versa"
version = "0.1.7"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
license = "MIT"
keywords = ["BNG", "OSGB36", "Geo"]
repository = "https://github.com/urschrei/rust_bng"
readme = "README.md"

[dependencies]
libc = "0.2.4"
rand = "0.3.13"
crossbeam = "0.2.0"
num_cpus = "0.2.10"

[lib]
name = "lonlat_bng"
crate-type = ["rlib", "dylib"]
test = true
doctest = false
doc = true

# [profile.release]
# debug = true

[[bin]]
name = "lonlat_bin"
doc = false
