[package]
name = "lonlat_bng"
description = "Convert longitude and latitude coordinates to BNG coordinates, and vice versa"
version = "0.1.3"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
license = "MIT"
keywords = ["BNG", "OSGB36", "Geo"]

[dependencies]
libc = "0.1.8"
rand = "0.3"

[lib]
name = "lonlat_bng"
crate-type = ["dylib", "staticlib"]
test = true
doctest = true
doc = true
